services:
  db:
    container_name: bookstore-postgres
    image: postgres
    environment:
      POSTGRES_USER: zildeus
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - 5432:5432
    networks:
        - db
    restart: unless-stopped
  backend:
    container_name: bookstore-api
    build: .
    ports:
      - 5000:5000
networks:
  db:
    driver: bridge
volumes:
  db:
